from django.urls import re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.conf import settings
from calisphere.home import HomeView
from . import views
from . import collection_views
from . import institution_views

app_name = 'calisphere'

urlpatterns = [
    re_path(r'^$', HomeView.as_view(), name='home'),
    re_path(r'^select-index/(?P<index>.*)/', views.select_index, name='select_index'),
    re_path(r'^search/$', views.search, name='search'),
    re_path(r'^item/(?P<item_id>.*)/$', views.item_view, name='itemView'),
    re_path(r'^collections/$',
        collection_views.collections_directory,
        name='collectionsDirectory'),
    re_path(r'^collections/(?P<collection_letter>[a-zA-Z]{1})/$',
        collection_views.collections_az,
        name='collectionsAZ'),
    re_path(r'^collections/(?P<collection_letter>num)/$',
        collection_views.collections_az,
        name='collectionsAZ'),
    re_path(r'^collections/(?P<collection_id>\d*)/$',
        collection_views.collection_search,
        name='collectionView'),
    re_path(r'^collections/(?P<collection_id>\d*)/reports/(?P<facet>[^/].*)/(?P<facet_value>.*)/$',
        views.report_collection_facet_value,
        name='reportCollectionFacetValue'),
    re_path(r'^collections/(?P<collection_id>\d*)/reports/(?P<facet>.*)/$',
        views.report_collection_facet,
        name='reportCollectionFacet'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<cluster>[^/].*)/(?P<cluster_value>.*)/$',
        collection_views.collection_facet_value,
        name='collectionFacetValue'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<facet>.*)/$',
        collection_views.collection_facet,
        name='collectionFacet'),
    re_path(r'^collections/(?P<collection_id>\d*)/(?P<facet>.*).json$',
        collection_views.collection_facet_json,
        name='collectionFacetJson'),

    # Redirects to new 'exhibitions'
    re_path(r'^collections/themed/$',
        RedirectView.as_view(url='/exhibitions/'),
        name='themedCollections'),
    re_path(r'^collections/cal-cultures/$',
        RedirectView.as_view(url='/cal-cultures/'),
        name='calCultures'),
    re_path(r'^collections/jarda/$',
        RedirectView.as_view(url='/exhibitions/t11/jarda/'),
        name='jarda'),
    re_path(r'^collections/titleSearch/$',
        collection_views.collections_search,
        name='collectionsTitleSearch'),
    re_path(r'^collections/titles.json$',
        collection_views.collections_titles,
        name='collectionsTitleData'),

    re_path(r'^institution/(?P<repository_id>\d*)/$',
        institution_views.repository_collections,
        name='repositoryCollections'),
    re_path(r'^institution/(?P<repository_id>\d*)/collections/$',
        institution_views.repository_collections,
        name='repositoryCollections'),
    re_path(r'^institution/(?P<repository_id>\d*)/items/$',
        institution_views.repository_search,
        name='repositorySearch'),

    re_path(r'^(?P<campus_slug>UC\w{1,2})/$',
        institution_views.campus_collections,
        name='campusCollections'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/collections/$',
        institution_views.campus_collections,
        name='campusCollections'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/items/$',
        institution_views.campus_search,
        name='campusSearch'),
    re_path(r'^(?P<campus_slug>UC\w{1,2})/institutions/$',
        institution_views.campus_institutions,
        name='campusInstitutions'),

    re_path(r'^institutions/$', institution_views.campus_directory, name='campusDirectory'),
    re_path(r'^institutions/statewide-partners/$',
        institution_views.statewide_directory,
        name='statewideDirectory'),
    re_path(r'about/$',
        TemplateView.as_view(template_name='calisphere/about.html'),
        name='about'),
    re_path(r'help/$',
        TemplateView.as_view(template_name='calisphere/help.html'),
        name='help'),
    re_path(r'terms/$',
        TemplateView.as_view(template_name='calisphere/termsOfUse.html'),
        name='termsOfUse'),
    re_path(r'privacy/$',
        TemplateView.as_view(template_name='calisphere/privacyStatement.html'),
        name='privacyStatement'),
    re_path(r'outreach/$',
        TemplateView.as_view(template_name='calisphere/outreach.html'),
        name='outreach'),
    re_path(r'contribute/$',
        TemplateView.as_view(template_name='calisphere/contribute.html'),
        name='contribute'),
    re_path(r'jobs/$',
        TemplateView.as_view(template_name='calisphere/jobs.html'),
        name='jobs'),
    re_path(r'overview/$', 
        TemplateView.as_view(template_name='calisphere/overview.html'),
        name='overview'),
    re_path(r'posters/$', views.posters, name='posters'),
    re_path(r'sitemap-(?P<section>.*).xml$', views.sitemap_section),
    re_path(r'sitemap-(?P<section>.*).xml.gz$', views.sitemap_section_zipped),

    # AJAX HELPERS
    re_path(r'^relatedCollections/',
        views.related_collections,
        name='relatedCollections'),
    re_path(r'^relatedExhibitions',
        views.related_exhibitions,
        name='relatedExhibitions'),
    re_path(r'^carousel/', views.item_view_carousel, name='carousel'),
    re_path(r'^contactOwner/', views.contact_owner, name='contactOwner'),
]

if settings.UCLDC_METADATA_SUMMARY:
    urlpatterns.insert(0,
        re_path(r'^collections/(?P<collection_id>\d*)/metadata/$',
            collection_views.collection_metadata,
            name='collectionMetadata'),
    )
    urlpatterns.insert(0,
        re_path(r'^collections/(?P<collection_id>\d*)/browse/$',
            collection_views.collection_browse,
            name='collectionBrowse'),)
